.pragma library
// Spanish UI text for Gaming Deck: keys are the English strings of shell.qml (and the
// fixed sentences the backend shows), exactly. Missing keys fall back to English.
var ES = {
    "  Proton was changed for a run: RESTORE PROTON when done.": "  Se cambió el Proton para una prueba: pulsa RESTAURAR PROTON al terminar.",
    "  ·  Proton: ": "  ·  Proton: ",
    "  ·  last ": "  ·  última ",
    "  ·  last driver update ": "  ·  última actualización del driver ",
    "  ·  latest: ": "  ·  última: ",
    "  ·  menu ": "  ·  menú ",
    "  ·  on/off ": "  ·  on/off ",
    "  ·  up to date": "  ·  al día",
    "  ·  used ": "  ·  usado ",
    "  · default profile": "  · perfil por defecto",
    "  —  nothing is changed from here: copy the command and run it in a terminal": "  —  desde aquí no se cambia nada: copia el comando y ejecútalo en una terminal",
    "  →  new version ": "  →  nueva versión ",
    " (a shader in your library, not in this look) didn't build — harmless: ": " (un shader de tu biblioteca que no está en este look) no compiló; no afecta: ",
    " (added).": " (añadidos).",
    " (applies the next time the game starts)": " (se aplica la próxima vez que abras el juego)",
    " (newest)": " (más reciente)",
    " (no upgrades: GE-Proton or Proton-CachyOS do)": " (sin mejoras: GE-Proton o Proton-CachyOS sí las tienen)",
    " (set automatically)": " (se ajusta solo)",
    " (supports upgrades)": " (admite mejoras)",
    " (you already had them).": " (ya los tenías).",
    " DLL. SAVE to apply.": " DLL. GUARDAR para aplicar.",
    " Download the mod's preset file (.ini) too and IMPORT it.": " Descarga también el archivo del preset del mod (.ini) e IMPÓRTALO.",
    " FILE": " ARCHIVO",
    " GAME(S)…": " JUEGO(S)…",
    " GAMES": " JUEGOS",
    " GPU or aren't set up here yet": " o aún no están configurados en este PC",
    " Its guide, mapped to the deck, is under SAVED below.": " Su guía, adaptada a la app, está abajo en GUARDADOS.",
    " Its menu: INSERT (Page Down if INSERT is your shader key).": " Su menú: INSERT (Av Pág si INSERT es tu tecla de shaders).",
    " MORE ▾": " MÁS ▾",
    " Proton builds available": " versiones de Proton disponibles",
    " READY": " LISTOS",
    " RESULTS": " RESULTADOS",
    " Shaders come from the packages the official ReShade installer lists.": " Los shaders vienen de los paquetes que lista el instalador oficial de ReShade.",
    " This game has FSR 3.1: the plain FSR 4 chip is simpler.": " Este juego trae FSR 3.1: el chip FSR 4 normal es más sencillo.",
    " backups in ~/gaming-deck-backups/prefixes": " copias en ~/gaming-deck-backups/prefixes",
    " belong to games that are no longer installed.": " son de juegos que ya no están instalados.",
    " can be cleaned (SHADERS)": " se pueden limpiar (SHADERS)",
    " didn't build the last time you played, so it isn't applied: ": " no compiló la última vez que jugaste, así que no se aplica: ",
    " downloads": " descargas",
    " downloads)": " descargas)",
    " effect": " efecto",
    " effects": " efectos",
    " effects)": " efectos)",
    " free of ": " libres de ",
    " from reshade.me, d3dcompiler_47 (Mozilla's Firefox installer, checksum-verified, like winetricks) and the standard shaders.": " desde reshade.me, d3dcompiler_47 (del instalador de Firefox de Mozilla, verificado, como winetricks) y los shaders estándar.",
    " in any Steam game": " en cualquier juego de Steam",
    " in orphans (no game uses them)": " en huérfanos (ningún juego los usa)",
    " is ": " es ",
    " is missing and isn't in any known pack → import the preset again": " falta y no está en ningún pack conocido → importa de nuevo el preset",
    " is missing here → install ": " falta aquí → instalar ",
    " is out (you have ": " ya está disponible (tienes la ",
    " min played": " min jugados",
    " mods on": " mods activos",
    " of 5 done — next: ": " de 5 hechos — siguiente: ",
    " of driver caches weren't used since the last driver update: they are stale. ": " de cachés del driver no se han usado desde la última actualización del driver: están obsoletas. ",
    " opens ReShade's menu — tweak values, switch effects on/off; changes are saved to this game's preset.": " abre el menú de ReShade: ajusta valores y activa o desactiva efectos; los cambios se guardan en el preset de este juego.",
    " orphan(s) (PREFIXES)": " huérfano(s) (PREFIXES)",
    " players": " jugadores",
    " prefixes · ": " prefixes · ",
    " presets in this file: pick one": " presets en este archivo: elige uno",
    " presets · best: ": " presets · el mejor: ",
    " presets": " presets",
    " problem": " problema",
    " problem(s)": " problema(s)",
    " reports ↗": " informes ↗",
    " reports)": " informes)",
    " risk": " riesgo",
    " setting(s) don't fit this ": " ajuste(s) no encajan con esta GPU ",
    " shader file(s) from the archive": " archivo(s) de shader del archivo descargado",
    " similar players": " jugadores similares",
    " skipped": " omitidos",
    " switches all effects on/off. ": " activa o desactiva todos los efectos. ",
    " threads · ": " hilos · ",
    " through the deck · ": " por la app · ",
    " to set up": " por configurar",
    " turns the effects on/off to compare.": " activa o desactiva los efectos para comparar.",
    " updates": " actualizaciones",
    " uses ": ") usa ",
    " warning": " aviso",
    " warning(s)": " aviso(s)",
    " who say it works use it (": " que dicen que funciona lo usan (",
    " with shaders": " con shaders",
    " · NOT INSTALLED": " · NO INSTALADO",
    " · active": " · activo",
    " · click to put it back": " · pulsa para volver a ponerlo",
    " · confidence ": " · confianza ",
    " · depth: ": " · profundidad: ",
    " · idle": " · en reposo",
    " · keys apply the next time the game starts": " · las teclas se aplican la próxima vez que abras el juego",
    " · on now": " · puesto ahora",
    " · trending ": " · tendencia ",
    " · you =": " · tú =",
    " — in vkBasalt, effects that need the depth buffer are skipped": " — en vkBasalt se omiten los efectos que necesitan el buffer de profundidad",
    " — open it, download the file, then IMPORT…": " — ábrelo, descarga el archivo y pulsa IMPORTAR…",
    " — right-click removes it": " — clic derecho para quitarlo",
    "% leave it at the default": "% lo dejan por defecto",
    "% of ": "% de ",
    "). Games pick it up on their next launch.": "). Los juegos la usan en su próximo arranque.",
    "). Shaders hook into the game's rendering; an anti-cheat may treat that as a modification and ban the account. Use them only if you accept that risk — applying one here asks for confirmation.": "). Los shaders se enganchan al render del juego; un anti-cheat puede tomarlo como una modificación y banear la cuenta. Úsalos solo si aceptas ese riesgo: aplicar uno aquí pide confirmación.",
    "): not touched": "): no se toca",
    "+ LINK": "+ ENLACE",
    ", which ignores the level (only BFQ honours it).": ", que ignora el nivel (solo BFQ lo respeta).",
    "-only → remove": " solamente → quitar",
    ". Already in the profile.": ". Ya está en el perfil.",
    ". Change it any time below.": ". Cámbialo cuando quieras abajo.",
    ". Click to add, then SAVE.": ". Pulsa para añadir y luego GUARDAR.",
    ". Click to open.": ". Pulsa para abrir.",
    ". Shaders: the packages the official ReShade installer lists.": ". Shaders: los paquetes que lista el instalador oficial de ReShade.",
    ". You can switch any of them back on below.": ". Puedes volver a encender cualquiera abajo.",
    ".dll + d3dcompiler_47 linked in the game folder · OFF removes them": ".dll + d3dcompiler_47 enlazados en la carpeta del juego · OFF los quita",
    "// log output": "// registro",
    "/mo": "/mes",
    "0.1% low": "0,1% mínimo",
    "1% low": "1% mínimo",
    "2D game drawn with GDI (RPG Maker style): no shader tool can hook it.": "Juego 2D dibujado con GDI (estilo RPG Maker): ninguna herramienta de shaders puede engancharse.",
    "32-BIT LIBRARIES": "LIBRERÍAS DE 32 BITS",
    "32-bit TLS (online games)": "TLS de 32 bits (juegos online)",
    "32-bit audio": "audio de 32 bits",
    ": ReShade's menu, tick/untick effects and move sliders (saved to this game). ": ": menú de ReShade; marca o desmarca efectos y mueve los controles (se guarda en este juego). ",
    ": the panel is drawn by Hyprland, outside the game — safe": ": el panel lo dibuja Hyprland, fuera del juego — seguro",
    "; in vkBasalt, effects that need the depth buffer are skipped.": "; en vkBasalt se omiten los efectos que necesitan el buffer de profundidad.",
    "; value adapted to this PC": "; valor adaptado a este PC",
    "A CPU · GPU temperature line at the top right while the game runs (click-through, closes with the game)": "Una línea con la temperatura de CPU y GPU arriba a la derecha mientras juegas (no bloquea el ratón y se cierra con el juego)",
    "A Vulkan layer: simplest, no files in the game folder; presets are converted and effects that need depth are skipped.": "Una capa de Vulkan: lo más sencillo, sin archivos en la carpeta del juego; los presets se convierten y se omiten los efectos de profundidad.",
    "A Wine-staging memory option some games or anti-cheats need to start.": "Una opción de memoria de Wine-staging que algunos juegos o anti-cheats necesitan para arrancar.",
    "A Wine-staging memory option that lowers CPU overhead in some games.": "Una opción de memoria de Wine-staging que reduce el uso de CPU en algunos juegos.",
    "A launch option passed to the game itself: what it does depends on the game.": "Una opción de arranque para el propio juego: lo que hace depende del juego.",
    "A polkit rule so your user switches schedulers without a password (needed for WHILE PLAYING without prompts)": "Una regla de polkit para que tu usuario cambie de planificador sin contraseña (necesaria para MIENTRAS JUEGAS sin avisos)",
    "A preset you downloaded (Nexus Mods…): zip, 7z, rar or .ini. Its own shaders come along; its ReShade.ini/DLLs are ignored.": "Un preset que hayas descargado (Nexus Mods…): zip, 7z, rar o .ini. Sus shaders se instalan con él; su ReShade.ini y sus DLL se ignoran.",
    "A program that starts the game (a launcher, tool or script).": "Un programa que arranca el juego (un launcher, herramienta o script).",
    "A/B BENCHMARKS ARE FOR STEAM GAMES": "LAS PRUEBAS A/B SON PARA JUEGOS DE STEAM",
    "ACHIEVEMENT POP-UPS": "AVISOS DE LOGROS",
    "ACTIVE ✓": "ACTIVO ✓",
    "ADJUSTING PROFILES…": "AJUSTANDO PERFILES…",
    "AFTER": "DESPUÉS",
    "ALL MISSING": "TODO LO QUE FALTA",
    "ALL": "TODO",
    "AMD FidelityFX CAS: crisper image, almost free": "AMD FidelityFX CAS: imagen más nítida, casi gratis",
    "APPLY": "APLICAR",
    "APPLYING PRESET…": "APLICANDO PRESET…",
    "APPLYING…": "APLICANDO…",
    "AS IS": "TAL CUAL",
    "AT BOOT": "AL ARRANCAR",
    "Achievements (the easiest first, a pop-up when you unlock one), guides (the game's wiki read in the panel; EliteGuías and Steam guides in the browser) and your notes, over the game. Hyprland draws it: nothing goes into the game, so it is safe with anti-cheat. Esc or the key closes it.": "Logros (los más fáciles primero y un aviso al conseguir uno), guías (la wiki del juego se lee en el panel; EliteGuías y las guías de Steam en el navegador) y tus notas, encima del juego. Lo dibuja Hyprland: no entra nada en el juego, así que es seguro con anticheat. Se cierra con Esc o con la misma tecla.",
    "Active: ": "Activo: ",
    "An environment variable for Proton, the driver or the game.": "Una variable de entorno para Proton, el driver o el juego.",
    "An old preset file (SweetFX or ReShade 1–2): today's ReShade can't load it": "Un preset antiguo (SweetFX o ReShade 1–2): el ReShade actual no puede cargarlo",
    "As SweetFX DB lists them: the newest first": "Como los lista SweetFX DB: los más nuevos primero",
    "Avg FPS": "FPS medio",
    "BACKING UP + DELETING…": "COPIANDO + BORRANDO…",
    "BACKING UP…": "HACIENDO COPIA…",
    "BACKUP": "COPIA",
    "BACKUPS ↗": "COPIAS ↗",
    "BENCH": "PRUEBAS",
    "BEST": "MEJORES",
    "Back to the kernel's scheduler (asks for your password)": "Vuelve al planificador del kernel (pide tu contraseña)",
    "Battle.net client": "Cliente de Battle.net",
    "Battle.net game": "Juego de Battle.net",
    "Below: a QUICK LOOK, a SweetFX DB preset (APPLY), or one from Nexus: SEARCH NEXUS → download it → IMPORT…": "Abajo: un LOOK RÁPIDO, un preset de SweetFX DB (APLICAR) o uno de Nexus: BUSCAR EN NEXUS → descárgalo → IMPORTAR…",
    "Black and white, impossible to miss: to check the effects are drawn in this game. Then pick a real look.": "Blanco y negro, imposible de no ver: para comprobar que los efectos se dibujan en este juego. Después elige un look de verdad.",
    "Built-in look": "Look integrado",
    "CAS at full strength: set the game's own sharpening to 0 so it isn't sharpened twice.": "CAS a tope: pon la nitidez del propio juego a 0 para no enfocar dos veces.",
    "CHECK FOR THIS PC — ": "REVISAR PARA ESTE PC — ",
    "CHECK FOR THIS PC": "REVISAR PARA ESTE PC",
    "CHECK": "COMPROBAR",
    "CHECKING": "COMPROBANDO",
    "CHECKING…": "COMPROBANDO…",
    "CLARITY": "CLARIDAD",
    "CLEAN ORPHANS": "LIMPIAR HUÉRFANOS",
    "CLEAN STALE": "LIMPIAR OBSOLETAS",
    "CLEAN": "LIMPIAR",
    "CLEANING…": "LIMPIANDO…",
    "CLEAR": "BORRAR",
    "CLEARING…": "BORRANDO…",
    "CLOCK": "FRECUENCIA",
    "CLONE": "CLONAR",
    "CLONING…": "CLONANDO…",
    "CLOSE STEAM FIRST": "CIERRA STEAM ANTES",
    "CLOSING…": "CERRANDO…",
    "CONFIRM? (anti-cheat)": "¿CONFIRMAR? (anti-cheat)",
    "CONFIRM?": "¿CONFIRMAR?",
    "COPIED ✓": "COPIADO ✓",
    "COPY": "COPIAR",
    "CPU load %": "Carga de CPU %",
    "CPU · GPU temperature line at the top right while the game runs": "Línea de temperatura de CPU y GPU arriba a la derecha mientras juegas",
    "CPU · MEMORY": "CPU · MEMORIA",
    "CachyOS script: switches the power profile to performance while the game runs.": "Script de CachyOS: pone el perfil de energía en rendimiento mientras el juego está abierto.",
    "Choose a Gaming Deck backup (.json)": "Elige una copia de Gaming Deck (.json)",
    "Choose a downloaded ReShade preset": "Elige un preset de ReShade descargado",
    "Click to add, then SAVE · % of players who say it works · ProtonDB (ODbL) ": "Pulsa para añadir y luego GUARDAR · % de jugadores que dicen que funciona · ProtonDB (ODbL) ",
    "Click to switch it off": "Pulsa para apagarlo",
    "Close Steam, then USE IN STEAM.": "Cierra Steam y pulsa USAR EN STEAM.",
    "Close Steam, then press USE IN STEAM.": "Cierra Steam y pulsa USAR EN STEAM.",
    "Compiles shaders in the background (older DXVK forks only): less stutter, possible brief glitches.": "Compila los shaders en segundo plano (solo versiones antiguas de DXVK): menos tirones, posibles fallos visuales breves.",
    "DELETE always makes a backup first (a Steam game's prefix is recreated on its next launch — saves kept only in the prefix would be lost without it). CLONE copies the Wine prefix to ~/Games/prefixes (instant on Btrfs). Restore a backup: gaming-deck prefix restore <backup> <folder>.": "BORRAR siempre hace antes una copia (el prefix de un juego de Steam se recrea al lanzarlo y sin ella se perderían las partidas guardadas solo en el prefix). CLONAR copia el prefix de Wine a ~/Games/prefixes (instantáneo en Btrfs). Restaurar una copia: gaming-deck prefix restore <copia> <carpeta>.",
    "DELETE": "BORRAR",
    "DELETING…": "BORRANDO…",
    "DISK ": "DISCO ",
    "DLSS (newest)": "DLSS (más reciente)",
    "DLSS needs an NVIDIA RTX card.": "DLSS necesita una tarjeta NVIDIA RTX.",
    "DONE ✓": "HECHO ✓",
    "DOWNLOADING RESHADE…": "DESCARGANDO RESHADE…",
    "DRIVER CACHE": "CACHÉ DEL DRIVER",
    "DRIVER": "DRIVER",
    "Denoised luma sharpening: detail without boosting grain": "Nitidez de luminancia sin ruido: detalle sin aumentar el grano",
    "Do Not Disturb in swaync while you play; notifications wait in its panel": "No molestar en swaync mientras juegas; las notificaciones esperan en su panel",
    "Download it and fetch the shaders it needs; ReShade runs it as it is": "Lo descarga y baja los shaders que necesita; ReShade lo usa tal cual",
    "Download, fetch the shaders it needs and convert it for vkBasalt": "Lo descarga, baja los shaders que necesita y lo convierte para vkBasalt",
    "Downloaded from reshade.me into your user folder, no password.": "Se descarga de reshade.me a tu carpeta de usuario, sin contraseña.",
    "Downloads weighed by the review: light presets go up, strong ones down, empty or old-format ones to the end": "Descargas ponderadas por la revisión: los presets ligeros suben, los fuertes bajan, y los vacíos o de formato antiguo van al final",
    "Draws DirectX through OpenGL (WineD3D) instead of Vulkan: a fallback for old games with graphics glitches; usually slower.": "Dibuja DirectX con OpenGL (WineD3D) en vez de Vulkan: un recurso para juegos antiguos con fallos gráficos; suele ir más lento.",
    "Driver caches older than the last driver update, and caches of uninstalled games (rebuilt when needed).": "Cachés del driver anteriores a su última actualización y cachés de juegos desinstalados (se rehacen cuando hace falta).",
    "Drivers: ": "Drivers: ",
    "EMPTY": "VACÍO",
    "EXECUTABLE": "EJECUTABLE",
    "EXPORT": "EXPORTAR",
    "EXPORTING…": "EXPORTANDO…",
    "Elden Ring tool (installed separately) that removes the 60 FPS cap and adds ultrawide and camera options.": "Herramienta para Elden Ring (se instala aparte) que quita el límite de 60 FPS y añade ultrapanorámico y opciones de cámara.",
    "Every Steam game: the most downloaded ReShade preset on SweetFX Settings DB, the ReShade compatibility list (PCGamingWiki, which reshade.me links) and online/anti-cheat risk. SET UP installs ReShade with that preset — or SHARPEN + AA when there's none — and the depth settings the list gives. Anti-cheat games and games where ReShade is banned are never touched.": "Cada juego de Steam: el preset de ReShade más descargado de SweetFX Settings DB, la lista de compatibilidad de ReShade (PCGamingWiki, la que enlaza reshade.me) y el riesgo online o de anti-cheat. CONFIGURAR instala ReShade con ese preset (o NITIDEZ + AA si no hay ninguno) y los ajustes de profundidad de la lista. Los juegos con anti-cheat o donde ReShade está vetado nunca se tocan.",
    "Every preset you applied or imported for this game is kept here (with its shaders), so you can go back to it without downloading it again. ✕ removes it from the list.": "Cada preset que aplicas o importas para este juego se guarda aquí (con sus shaders), para volver a él sin descargarlo otra vez. ✕ lo quita de la lista.",
    "Every step, with what each one does": "Todos los pasos, con lo que hace cada uno",
    "Executable, graphics API and the in-game keys": "Ejecutable, API gráfica y teclas en el juego",
    "Experimental options of the AMD Vulkan driver (RADV): can help a game or make it worse.": "Opciones experimentales del driver Vulkan de AMD (RADV): pueden ayudar a un juego o empeorarlo.",
    "FAILED · ": "FALLÓ · ",
    "FILE": "ARCHIVO",
    "FILM FX": "EFECTOS DE CINE",
    "FIND AGAIN": "BUSCAR DE NUEVO",
    "FIX ALL": "ARREGLAR TODO",
    "FOLDER ↗": "CARPETA ↗",
    "FOLDER": "CARPETA",
    "FPS LIMIT": "LÍMITE FPS",
    "FROM A FILE": "DESDE ARCHIVO",
    "FSR 4 needs a Radeon RX 9000 (RDNA4) or RX 7000 with GE-Proton.": "FSR 4 necesita una Radeon RX 9000 (RDNA4) o una RX 7000 con GE-Proton.",
    "FSR 4 on a Radeon RX 7000 (RDNA 3) through a slower emulated path. Not needed on an RX 9000.": "FSR 4 en una Radeon RX 7000 (RDNA 3) mediante una vía emulada más lenta. En una RX 9000 no hace falta.",
    "FSR 4 runs on AMD Radeon RX 9000 (RDNA4) — not on this GPU.": "FSR 4 funciona en AMD Radeon RX 9000 (RDNA4), no en esta GPU.",
    "FSR 4 through OptiScaler is offered on Radeon RX 9000 (RDNA4).": "FSR 4 con OptiScaler se ofrece en Radeon RX 9000 (RDNA4).",
    "FSR 4 via OptiScaler": "FSR 4 vía OptiScaler",
    "Frames": "Fotogramas",
    "From SweetFX Settings DB (sfx.thelazy.net), made for ReShade": "De SweetFX Settings DB (sfx.thelazy.net), hechos para ReShade",
    "From SweetFX Settings DB": "De SweetFX Settings DB",
    "From chaotic-aur (asks for your password) plus the standard shaders.": "Desde chaotic-aur (pide tu contraseña) y los shaders estándar.",
    "GAME": "JUEGO",
    "GAMEMODE is on but GameMode isn't installed → install it": "GAMEMODE está activado pero GameMode no está instalado → instálalo",
    "GAMING TOOLS": "HERRAMIENTAS",
    "GAMMA": "GAMMA",
    "GET DATA (70 MB)": "DESCARGAR DATOS (70 MB)",
    "GPU DRIVER": "DRIVER DE GPU",
    "GPU LOAD": "CARGA GPU",
    "GPU load %": "Carga de GPU %",
    "GPU max °C": "GPU máx °C",
    "GUIDE ▴": "GUÍA ▴",
    "GUIDE ▾": "GUÍA ▾",
    "Game profiles, shader looks, saved preset pages, keys and the CPU scheduler setting, to ~/gaming-deck-backup-<date>.json. IMPORT adds what this PC lacks (a Control Deck backup works too); then CHECK FOR THIS PC in LIBRARY adapts it.": "Perfiles de juego, looks de shaders, páginas de presets guardadas, teclas y el ajuste del planificador de CPU, en ~/gaming-deck-backup-<fecha>.json. IMPORTAR añade lo que falta en este PC (también vale una copia de Control Deck); después, CHECK FOR THIS PC en BIBLIOTECA lo adapta.",
    "GameMode active": "GameMode activo",
    "GameMode has it on performance": "GameMode lo tiene en rendimiento",
    "GameMode isn't installed on this PC: this does nothing. HEALTH or CHECK FOR THIS PC installs it.": "GameMode no está instalado en este PC: esto no hace nada. SALUD o CHECK FOR THIS PC lo instalan.",
    "GameMode switches it to performance while you play": "GameMode lo pone en rendimiento mientras juegas",
    "GameMode: raises CPU priority and switches to the performance governor while you play.": "GameMode: sube la prioridad de la CPU y pone el modo de rendimiento mientras juegas.",
    "Games launched through the deck (Steam) or Umbral 0.10+.": "Juegos lanzados con la app (Steam) o con Umbral 0.10+.",
    "Get the data once to see what players with hardware like yours use.": "Descarga los datos una vez para ver qué usan los jugadores con un hardware como el tuyo.",
    "HEALTH →": "SALUD →",
    "HEALTH": "SALUD",
    "HELD BACK BY": "LIMITADA POR",
    "HISTORY": "HISTORIAL",
    "HOLD NOTIFICATIONS": "RETENER NOTIFICACIONES",
    "Has online modes without anti-cheat: fine for single-player; check the game's rules online.": "Tiene modos online sin anti-cheat: bien para un jugador; revisa las normas del juego online.",
    "How many CPU cores the game sees: fixes games that stutter or crash with many cores.": "Cuántos núcleos de CPU ve el juego: arregla juegos que van a tirones o se cierran con muchos núcleos.",
    "How much this preset changes the game's look": "Cuánto cambia este preset el aspecto del juego",
    "Hyprland animations, blur and shadows off while you play, back as they were after": "Animaciones, desenfoque y sombras de Hyprland apagados mientras juegas; después vuelven como estaban",
    "Hyprland/HyDE and most desktops take PrtSc for their own screenshots: then the game never gets it": "Hyprland/HyDE y la mayoría de escritorios usan Impr Pant para sus propias capturas: entonces el juego nunca la recibe",
    "IMPORTING PRESET…": "IMPORTANDO PRESET…",
    "IMPORTING…": "IMPORTANDO…",
    "IMPORT…": "IMPORTAR…",
    "IN USE": "EN USO",
    "IN-GAME PANEL": "PANEL EN EL JUEGO",
    "INDEXING PROTONDB DATA…": "INDEXANDO DATOS DE PROTONDB…",
    "INSTALL ": "INSTALAR ",
    "INSTALL": "INSTALAR",
    "INSTALLING ": "INSTALANDO ",
    "INSTALLING GE-PROTON…": "INSTALANDO GE-PROTON…",
    "INSTALLING SHADERS…": "INSTALANDO SHADERS…",
    "INSTALLING…": "INSTALANDO…",
    "IO PRIORITY": "PRIORIDAD E/S",
    "If you use one anyway, vkBasalt is the lighter touch: a Vulkan layer, no DLL or files in the game folder.": "Si aun así usas uno, vkBasalt es lo menos invasivo: una capa de Vulkan, sin DLL ni archivos en la carpeta del juego.",
    "Imported from ": "Importado de ",
    "Imported preset": "Preset importado",
    "In game: ": "En el juego: ",
    "Inherited from the prefix. Click to set it on this game.": "Heredado del prefix. Pulsa para fijarlo en este juego.",
    "Install ": "Instalar ",
    "Install ReShade next to this .exe (detected API: ": "Instalar ReShade junto a este .exe (API detectada: ",
    "Installed: the preset in use was imported from this mod's file.": "Instalado: el preset en uso se importó del archivo de este mod.",
    "Its Steam launch options go through the deck, which loads the shaders.": "Sus opciones de lanzamiento de Steam pasan por la app, que carga los shaders.",
    "JOIN GROUP": "UNIRSE AL GRUPO",
    "JOINING…": "UNIÉNDOSE…",
    "KEY": "TECLA",
    "Keep a preset page for this game": "Guardar una página de preset para este juego",
    "Key removed from Hyprland's config.": "Tecla quitada de la configuración de Hyprland.",
    "LAST SESSIONS": "ÚLTIMAS PARTIDAS",
    "LAUNCH": "LANZAR",
    "LAUNCHING…": "LANZANDO…",
    "LAVD GAMING NOW": "LAVD GAMING YA",
    "LESS ▴": "MENOS ▴",
    "LIBRARY · STORAGE": "BIBLIOTECA · ALMACENAMIENTO",
    "LIBRARY": "BIBLIOTECA",
    "LIGHT": "SUAVE",
    "LIGHTER": "MÁS SUAVE",
    "LIVE": "EN VIVO",
    "LOAD": "CARGA",
    "LOOKING FOR PREFIXES…": "BUSCANDO PREFIXES…",
    "Launch it from Umbral": "Lánzalo desde Umbral",
    "Launch it through Gaming Deck": "Lánzalo a través de Gaming Deck",
    "Launch options are set in Umbral. Gaming Deck adds TEMPS and shaders when Umbral 0.10.0+ starts the game.": "Las opciones de lanzamiento se configuran en Umbral. Gaming Deck añade TEMPS y shaders cuando Umbral 0.10.0+ arranca el juego.",
    "Launch the game and press ": "Lanza el juego y pulsa ",
    "Launch the game; ": "Lanza el juego; ",
    "Lets DirectX games running through DXVK see HDR. Needs an HDR monitor and Wayland or gamescope.": "Deja que los juegos DirectX que van por DXVK vean el HDR. Necesita un monitor HDR y Wayland o gamescope.",
    "Lets the game output HDR. Needs an HDR monitor and Wayland (PROTON_ENABLE_WAYLAND) or gamescope.": "Deja que el juego saque HDR. Necesita un monitor HDR y Wayland (PROTON_ENABLE_WAYLAND) o gamescope.",
    "Light anti-aliasing, softer edges": "Antialiasing ligero, bordes más suaves",
    "Loading presets…": "Cargando presets…",
    "MAINTENANCE": "MANTENIMIENTO",
    "MANGOHUD": "MANGOHUD",
    "MEASURE": "MEDIR",
    "MEASURING CACHES…": "MIDIENDO CACHÉS…",
    "MENU KEY": "TECLA MENÚ",
    "MODERATE": "MODERADO",
    "MODS": "MODS",
    "MORE ▾": "MÁS ▾",
    "MOST DOWNLOADED": "MÁS DESCARGADOS",
    "MOVING RESHADE…": "MOVIENDO RESHADE…",
    "MY LIBRARY": "MI BIBLIOTECA",
    "MY LOOKS ⓘ": "MIS LOOKS ⓘ",
    "Made for the old SweetFX injector, not ReShade: it can't be applied": "Hecho para el antiguo SweetFX, no para ReShade: no se puede aplicar",
    "Makes the game believe it runs on a Steam Deck: some games then pick Deck settings, a controller layout or skip their launcher.": "Hace creer al juego que está en una Steam Deck: algunos juegos eligen entonces ajustes de Deck, un esquema de mando o se saltan su launcher.",
    "Makes the game use DirectX 11: sometimes more stable or faster under Proton.": "Hace que el juego use DirectX 11: a veces más estable o más rápido con Proton.",
    "Makes the game use DirectX 12.": "Hace que el juego use DirectX 12.",
    "Many effects: more GPU cost and more ways to look off.": "Muchos efectos: más carga para la GPU y más formas de que se vea raro.",
    "Mesa + Intel Vulkan": "Mesa + Intel Vulkan",
    "Mesa + RADV Vulkan": "Mesa + RADV Vulkan",
    "NEEDS DEPTH": "USA PROFUNDIDAD",
    "NEW": "NUEVO",
    "NEWEST": "MÁS NUEVOS",
    "NO ANIMATIONS / BLUR": "SIN ANIMACIONES / DESENFOQUE",
    "NO DATA": "SIN DATOS",
    "NO GAMES FOUND": "NO SE ENCONTRARON JUEGOS",
    "NO KEY": "SIN TECLA",
    "NO PASSWORD": "SIN CONTRASEÑA",
    "NO RUNS YET": "AÚN NO HAY PRUEBAS",
    "NO SHADER CACHES": "NO HAY CACHÉS DE SHADERS",
    "NO WINE/PROTON PREFIXES FOUND": "NO HAY PREFIXES DE WINE/PROTON",
    "NONE": "NINGUNO",
    "NVIDIA kernel module": "módulo del kernel NVIDIA",
    "NVIDIA userspace": "NVIDIA (espacio de usuario)",
    "NVIDIA versions": "versiones de NVIDIA",
    "Native Linux build that draws with OpenGL: neither vkBasalt (Vulkan only) nor ReShade (Windows only) can hook it.": "Versión nativa de Linux que dibuja con OpenGL: ni vkBasalt (solo Vulkan) ni ReShade (solo Windows) pueden engancharse.",
    "Native Linux build that draws with Vulkan: vkBasalt is the only one that can hook it (ReShade needs a Windows game).": "Versión nativa de Linux que dibuja con Vulkan: vkBasalt es el único que puede engancharse (ReShade necesita un juego de Windows).",
    "Needs Umbral 0.10.0 or newer (it asks the deck before launching): update Umbral.": "Necesita Umbral 0.10.0 o posterior (pregunta a la app antes de lanzar): actualiza Umbral.",
    "Needs dunst or swaync running": "Necesita dunst o swaync en marcha",
    "No ProtonDB report with launch options for this game yet.": "Aún no hay informes de ProtonDB con opciones de lanzamiento para este juego.",
    "No ReShade preset in that file (it needs a Techniques= line).": "No hay ningún preset de ReShade en ese archivo (necesita una línea Techniques=).",
    "No ReShade presets on SweetFX DB → SET UP uses SHARPEN + AA": "No hay presets de ReShade en SweetFX DB → CONFIGURAR usa NITIDEZ + AA",
    "No effect here: this game's disk ": "Aquí no hace nada: el disco de este juego (",
    "No effects in it: it changes nothing": "No tiene efectos: no cambia nada",
    "No game with that name on SweetFX Settings DB: try another name, or use a quick look.": "No hay ningún juego con ese nombre en SweetFX Settings DB: prueba otro nombre o usa un look rápido.",
    "No key: effects stay on": "Sin tecla: los efectos quedan siempre activos",
    "No mods yet (Crisol)": "Aún sin mods (Crisol)",
    "No preset in that file, only shaders: ": "No hay preset en ese archivo, solo shaders: ",
    "No upscaler upgrade for this game ⓘ": "No hay mejoras de escalado para este juego ⓘ",
    "Not a key (e.g. F6, SUPER + G)": "No es una tecla (p. ej. F6, SUPER + G)",
    "Not installed on this PC: install it first, or the game won't start with it.": "No está instalado en este PC: instálalo antes o el juego no arrancará con él.",
    "Nothing is used by enough similar players to recommend it. ": "Nada lo usan suficientes jugadores similares como para recomendarlo. ",
    "OFF": "NO",
    "OLD FORMAT": "FORMATO ANTIGUO",
    "OLD SWEETFX": "SWEETFX ANTIGUO",
    "ON": "SÍ",
    "ON-SCREEN CHECK": "MARCA EN PANTALLA",
    "ON/OFF KEY": "TECLA ON/OFF",
    "OPEN ": "ABRIR ",
    "OPEN FOLDER": "ABRIR CARPETA",
    "OPEN IN CRISOL": "ABRIR EN CRISOL",
    "OPEN": "ABRIR",
    "OPENING…": "ABRIENDO…",
    "ORPHAN": "HUÉRFANO",
    "OVER-SHARP": "EXCESO DE NITIDEZ",
    "OVERLAY": "OVERLAY",
    "One-time setup, no password: ReShade ": "Configuración inicial, sin contraseña: ReShade ",
    "One-time setup: vkBasalt (the Vulkan layer that draws the effects, 64 + 32-bit, from chaotic-aur) and the standard ReShade shaders (official packages, ~0.5 MB). Works the same on AMD and NVIDIA.": "Configuración inicial: vkBasalt (la capa de Vulkan que dibuja los efectos, 64 y 32 bits, desde chaotic-aur) y los shaders estándar de ReShade (paquetes oficiales, ~0,5 MB). Funciona igual en AMD y NVIDIA.",
    "Online game with anti-cheat: OptiScaler hooks the game, not worth a ban.": "Juego online con anti-cheat: OptiScaler se engancha al juego, no merece un baneo.",
    "Only change it if ReShade doesn't show up in game": "Cámbialo solo si ReShade no aparece en el juego",
    "Only on Hyprland": "Solo en Hyprland",
    "Only sets variables before the game starts (the variables are the useful part).": "Solo pone variables antes de arrancar el juego (lo útil son las variables).",
    "Open the folder with this game's preset": "Abre la carpeta con el preset de este juego",
    "Open the preset's page": "Abrir la página del preset",
    "Opened in your browser.": "Abierto en el navegador.",
    "OptiScaler needs the game to offer DLSS, XeSS or FSR 2/3.1 to take over — none found.": "OptiScaler necesita que el juego ofrezca DLSS, XeSS o FSR 2/3.1 para sustituirlo, y no trae ninguno.",
    "OptiScaler takes over the game's DLSS / XeSS / FSR and renders it with FSR 4 — pick that upscaler in the game's settings. Proton downloads everything; nothing to install.": "OptiScaler toma el DLSS / XeSS / FSR del juego y lo renderiza con FSR 4: elige ese escalado en las opciones del juego. Proton lo descarga todo; no hay que instalar nada.",
    "Options for VKD3D-Proton (DirectX 12 → Vulkan), e.g. dxr to turn ray tracing on.": "Opciones de VKD3D-Proton (DirectX 12 → Vulkan), p. ej. dxr para activar el ray tracing.",
    "Orphan prefixes": "Prefixes huérfanos",
    "Own game": "Juego propio",
    "PICK A GAME IN LIBRARY FIRST": "ELIGE ANTES UN JUEGO EN BIBLIOTECA",
    "PICK A STEAM OR UMBRAL GAME IN LIBRARY": "ELIGE UN JUEGO DE STEAM O UMBRAL EN BIBLIOTECA",
    "PLAY WITH MODS": "JUGAR CON MODS",
    "PLAY": "JUGAR",
    "POWER": "CONSUMO",
    "PRESS SCAN": "PULSA SCAN",
    "PREVIEW": "VISTA PREVIA",
    "PROFILE": "PERFIL",
    "PRT SC": "IMPR PANT",
    "Pauses dunst while you play; what arrived shows when the game closes": "Pausa dunst mientras juegas; lo que haya llegado aparece al cerrar el juego",
    "Pick a look": "Elige un look",
    "Pins the game to some CPU cores only: for games that run badly on many cores.": "Fija el juego a solo algunos núcleos de CPU: para juegos que van mal con muchos núcleos.",
    "Play and tweak": "Juega y ajusta",
    "Players don't agree on any launch option for this game.": "Los jugadores no coinciden en ninguna opción de lanzamiento para este juego.",
    "Presets: SweetFX Settings DB (sfx.thelazy.net), made for ReShade": "Presets: SweetFX Settings DB (sfx.thelazy.net), hechos para ReShade",
    "Press USE IN STEAM.": "Pulsa USAR EN STEAM.",
    "Proton builds in compatibilitytools.d no Steam game, Umbral prefix or running game uses.": "Versiones de Proton en compatibilitytools.d que no usa ningún juego de Steam, prefix de Umbral ni juego en marcha.",
    "Proton reads controllers through SDL instead of its own code: fixes some controllers that aren't detected or are mapped wrong.": "Proton lee los mandos con SDL en vez de con su propio código: arregla mandos que no se detectan o tienen los botones mal.",
    "Proton swaps in the newest ": "Proton pone la versión más reciente de ",
    "Proton with extra game fixes, and the FSR 4 / DLSS / XeSS upgrades of UPSCALE. Checksum-verified; restart Steam to see it.": "Proton con arreglos extra para juegos y las mejoras FSR 4 / DLSS / XeSS de ESCALADO. Se comprueba su suma de verificación; reinicia Steam para verlo.",
    "ProtonDB's open data (every game's reported launch options), indexed locally to ≈5 MB": "Datos abiertos de ProtonDB (las opciones de lanzamiento de cada juego), indexados en local en ≈5 MB",
    "ProtonDB: score ": "ProtonDB: puntuación ",
    "QUICK LOOK": "LOOK RÁPIDO",
    "RAM · VRAM %": "RAM · VRAM %",
    "READING YOUR LIBRARY…": "LEYENDO TU BIBLIOTECA…",
    "READING…": "LEYENDO…",
    "RECENTLY PLAYED": "JUGADO RECIENTEMENTE",
    "RECHECK": "VOLVER A COMPROBAR",
    "REFRESH RESULTS": "ACTUALIZAR RESULTADOS",
    "REFRESH": "ACTUALIZAR",
    "REMOVE SHADERS": "QUITAR SHADERS",
    "REMOVE?": "¿QUITAR?",
    "REMOVING LINK…": "QUITANDO ENLACE…",
    "REMOVING…": "QUITANDO…",
    "RESET": "RESTABLECER",
    "RESETTING…": "RESTABLECIENDO…",
    "RESTORE PROTON": "RESTAURAR PROTON",
    "RESTORE STEAM": "RESTAURAR STEAM",
    "RESTORE": "RESTAURAR",
    "RESTORING…": "RESTAURANDO…",
    "REVIEW": "REVISAR",
    "REVIEWING ": "REVISANDO ",
    "ROM (emulator)": "ROM (emulador)",
    "ROUTE": "VÍA",
    "RUN ": "PRUEBA ",
    "RUN A": "PROBAR A",
    "RUN B": "PROBAR B",
    "RUN starts the game from Steam; MangoHud records every frame after the delay, for the measured time. Play the same scene in both runs, quit the game, then REFRESH. Variants changing Proton need Steam closed.": "PROBAR A/B lanza el juego desde Steam; MangoHud registra cada fotograma tras la espera, durante el tiempo medido. Juega la misma escena en las dos pruebas, cierra el juego y pulsa ACTUALIZAR. Las variantes que cambian de Proton necesitan Steam cerrado.",
    "RUNNING NOW": "EN EJECUCIÓN",
    "RUNNING": "EN EJECUCIÓN",
    "RX 7000 (RDNA3) needs GE-Proton's RDNA3 variant.": "RX 7000 (RDNA3) necesita la variante RDNA3 de GE-Proton.",
    "ReShade isn't installed in its folder on this PC → set it up": "ReShade no está instalado en su carpeta en este PC → configúralo",
    "ReShade itself: presets exactly as made (depth effects too) and its in-game menu. For D3D9–12 and OpenGL games.": "ReShade de verdad: los presets tal cual se hicieron (con efectos de profundidad) y su menú en el juego. Para juegos D3D9–12 y OpenGL.",
    "ReShade not installed": "ReShade no instalado",
    "Reading ": "Leyendo ",
    "Recommended here: ": "Recomendado aquí: ",
    "Record each game session and notify a summary when it ends": "Registra cada partida y avisa con un resumen al terminar",
    "Remove from MY LOOKS (the game keeps its current look)": "Quitar de MIS LOOKS (el juego mantiene su look actual)",
    "Remove the shaders from this game": "Quitar los shaders de este juego",
    "Replaces the game's FSR 3.1 with FSR 4 (much sharper upscaling). Needs a Radeon RX 9000 (RDNA 4) and a Proton that supports it (GE, CachyOS).": "Cambia el FSR 3.1 del juego por FSR 4 (un escalado mucho más nítido). Necesita una Radeon RX 9000 (RDNA 4) y un Proton que lo soporte (GE, CachyOS).",
    "Restart the PC": "Reinicia el PC",
    "Route: ": "Vía: ",
    "Run INSTALL above first": "Pulsa antes INSTALAR arriba",
    "Runs the game as a native Wayland window instead of through XWayland: can lower latency and fix scaling; some games, overlays or launchers don't like it.": "Abre el juego como ventana nativa de Wayland en vez de por XWayland: puede bajar la latencia y arreglar el escalado; a algunos juegos, overlays o launchers no les gusta.",
    "SAVE": "GUARDAR",
    "SAVED": "GUARDADOS",
    "SAVING LINK…": "GUARDANDO ENLACE…",
    "SAVING…": "GUARDANDO…",
    "SCAN": "ESCANEAR",
    "SCANNING YOUR LIBRARY…": "ESCANEANDO TU BIBLIOTECA…",
    "SCANNING…": "ESCANEANDO…",
    "SCHEDULER": "PLANIFICADOR",
    "SCHEDULER…": "PLANIFICADOR…",
    "SCREENSHOT KEY": "TECLA CAPTURA",
    "SEARCH NEXUS ↗": "BUSCAR EN NEXUS ↗",
    "SEARCH": "BUSCAR",
    "SEARCHING…": "BUSCANDO…",
    "SET UP ALL (": "CONFIGURAR TODO (",
    "SET UP": "CONFIGURAR",
    "SET WIKI": "CAMBIAR WIKI",
    "SET": "PONER",
    "SETTING KEY…": "CAMBIANDO TECLA…",
    "SETTING PROTON…": "CAMBIANDO PROTON…",
    "SETTING UP ": "CONFIGURANDO ",
    "SETTING UP RESHADE…": "CONFIGURANDO RESHADE…",
    "SETTINGS ▴": "AJUSTES ▴",
    "SETTINGS ▾": "AJUSTES ▾",
    "SHADER CACHES": "CACHÉS DE SHADERS",
    "SHARED": "COMPARTIDO",
    "SHARP 100 %": "NITIDEZ 100 %",
    "SHARPEN + AA": "NITIDEZ + AA",
    "SHARPEN": "NITIDEZ",
    "SMAA anti-aliasing, then CAS sharpening": "Antialiasing SMAA y después nitidez CAS",
    "STALE": "OBSOLETA",
    "STATUS": "ESTADO",
    "STEAM DEFAULT": "POR DEFECTO DE STEAM",
    "STEPS": "PASOS",
    "STOP": "PARAR",
    "STORE": "TIENDA",
    "STRONG COLOUR": "COLOR FUERTE",
    "STRONG": "FUERTE",
    "SUMMARY OFF": "RESUMEN OFF",
    "SURE? CLICK AGAIN": "¿SEGURO? PULSA OTRA VEZ",
    "SWITCHING API…": "CAMBIANDO API…",
    "SWITCHING…": "CAMBIANDO…",
    "SYSTEM": "SISTEMA",
    "Saved in Hyprland's config (a backup of it is kept).": "Guardada en la configuración de Hyprland (se guarda una copia de seguridad).",
    "Saved in Umbral itself (it applies them at once if it's open). A · means it comes from the prefix; Battle.net's options are its prefix's.": "Se guardan en el propio Umbral (si está abierto, las aplica al momento). Un · indica que viene del prefix; las opciones de Battle.net son las de su prefix.",
    "ScummVM game": "Juego de ScummVM",
    "Set on this game. Click to switch it.": "Fijado en este juego. Pulsa para cambiarlo.",
    "Shader caches": "Cachés de shaders",
    "Ships: ": "Trae: ",
    "Shows the MangoHud overlay (FPS, frame time, temperatures) in the game.": "Muestra el overlay de MangoHud (FPS, tiempo de fotograma, temperaturas) en el juego.",
    "Shows the upscaler's own watermark in game, to confirm the upgrade is active": "Muestra la marca de agua del escalador en el juego, para confirmar que la mejora está activa",
    "Size of the NVIDIA shader cache: a bigger one means less stutter from recompiling shaders.": "Tamaño de la caché de shaders de NVIDIA: más grande significa menos tirones por recompilar shaders.",
    "Skips the intro videos.": "Se salta los vídeos de introducción.",
    "Some games quick-load with F9": "Algunos juegos cargan partida rápida con F9",
    "Spikes": "Picos",
    "Starts a Python script before the game (e.g. a game patcher): only useful if you have that script.": "Ejecuta un script de Python antes del juego (p. ej. un parcheador): solo sirve si tienes ese script.",
    "Steam (shared, non-Steam shortcuts)": "Steam (compartido, accesos no de Steam)",
    "Steam default": "Por defecto de Steam",
    "Steam is compiling shaders right now; cleaning waits until it finishes. ": "Steam está compilando shaders ahora mismo; la limpieza espera a que termine. ",
    "Steam must be closed to change it": "Steam tiene que estar cerrado para cambiarlo",
    "Steam takes screenshots with F12 by default": "Steam hace capturas con F12 por defecto",
    "Switch off what usually makes it look worse: ": "Apaga lo que suele hacer que se vea peor: ",
    "Switch to ": "Cambiar a ",
    "Switched off — click to switch it back on": "Apagado: pulsa para volver a encenderlo",
    "TEMPERATURE": "TEMPERATURA",
    "TEST (B/W)": "PRUEBA (B/N)",
    "THIS GAME": "ESTE JUEGO",
    "TOOL": "HERRAMIENTA",
    "TURNING OFF…": "DESACTIVANDO…",
    "Temperatures, load and power are sampled every 5 s while a game runs (Steam through the deck, Umbral 0.10+).": "Temperaturas, carga y consumo se miden cada 5 s mientras juegas (Steam a través de la app, Umbral 0.10+).",
    "That key is already used in Hyprland: ": "Esa tecla ya la usa Hyprland: ",
    "The game doesn't ship DLSS.": "El juego no trae DLSS.",
    "The game doesn't ship FSR 3.1 as a DLL (FSR 2/3.0 inside the .exe can't be swapped).": "El juego no trae FSR 3.1 como DLL (FSR 2/3.0 dentro del .exe no se puede sustituir).",
    "The game doesn't ship XeSS.": "El juego no trae XeSS.",
    "The game must launch through Gaming Deck: LIBRARY → USE IN STEAM first.": "El juego tiene que lanzarse a través de Gaming Deck: antes, BIBLIOTECA → USAR EN STEAM.",
    "The game reads and writes the disk ahead of other programs (ionice best-effort, level 0). It helps when something else uses the disk while you play: downloads, updates, copies.": "El juego lee y escribe en el disco por delante de otros programas (ionice best-effort, nivel 0). Ayuda si otra cosa usa el disco mientras juegas: descargas, actualizaciones, copias.",
    "The game renders with Vulkan: ReShade's DLL can't hook it here, vkBasalt can.": "El juego renderiza con Vulkan: la DLL de ReShade no puede engancharse aquí; vkBasalt sí.",
    "The game ships FSR 3.1 for Vulkan; the FSR 4 upgrade is DirectX 12 only.": "El juego trae FSR 3.1 para Vulkan; la mejora a FSR 4 es solo para DirectX 12.",
    "The game's FSR 3.1 runs as FSR 4 (AMD's ML upscaler). Proton downloads the DLL. SAVE to apply.": "El FSR 3.1 del juego pasa a funcionar como FSR 4 (el escalador con IA de AMD). Proton descarga la DLL. GUARDAR para aplicar.",
    "The game's developer mode (in Kingdom Come: the developer console).": "El modo desarrollador del juego (en Kingdom Come: la consola de desarrollador).",
    "The key most preset guides suggest": "La tecla que sugieren casi todas las guías de presets",
    "The most downloaded first": "Los más descargados primero",
    "The profile applies on every launch from Steam.": "El perfil se aplica cada vez que se lanza desde Steam.",
    "The recommended one for this game. ": "La recomendada para este juego. ",
    "This game has no presets yet.": "Este juego aún no tiene presets.",
    "This game is drawn in 2D with GDI (RPG Maker style), not with DirectX, OpenGL or Vulkan: neither ReShade nor vkBasalt can hook it. TEMPS still works (LIBRARY).": "Este juego se dibuja en 2D con GDI (estilo RPG Maker), no con DirectX, OpenGL ni Vulkan: ni ReShade ni vkBasalt pueden engancharse. TEMPS sí funciona (BIBLIOTECA).",
    "This game's Proton can't do it: pick GE-Proton or Proton-CachyOS in PROTON.": "El Proton de este juego no lo admite: elige GE-Proton o Proton-CachyOS en PROTON.",
    "This game's disk honours it: ": "El disco de este juego la respeta: ",
    "Turn on Performance Mode once you like it. Screenshots (PRINT SCREEN): ": "Activa Performance Mode cuando te guste. Capturas (IMPR PANT): ",
    "Turns esync off: a fallback for games that hang or crash with it.": "Desactiva esync: un recurso para juegos que se cuelgan o se cierran con él.",
    "Turns fsync off: a fallback for games that hang or crash with it.": "Desactiva fsync: un recurso para juegos que se cuelgan o se cierran con él.",
    "Turns on the Vulkan HDR layer (vk-hdr-layer) so HDR works on a Wayland desktop without gamescope.": "Activa la capa HDR de Vulkan (vk-hdr-layer) para que el HDR funcione en un escritorio Wayland sin gamescope.",
    "UP TO DATE ✓": "AL DÍA ✓",
    "UPDATE DATA": "ACTUALIZAR DATOS",
    "UPDATE": "ACTUALIZAR",
    "UPDATES": "ACTUALIZACIONES",
    "UPDATING…": "ACTUALIZANDO…",
    "UPSCALE": "ESCALADO",
    "USE IN STEAM moves these options into the profile (Steam must be closed).": "USAR EN STEAM pasa estas opciones al perfil (Steam tiene que estar cerrado).",
    "USE IN STEAM puts the deck in its launch options.": "USAR EN STEAM pone la app en sus opciones de lanzamiento.",
    "USE IN STEAM": "USAR EN STEAM",
    "USE RESHADE ★": "USAR RESHADE ★",
    "USE VKBASALT ★": "USAR VKBASALT ★",
    "Umbral asks the deck for the shaders/TEMPS each time it starts the game.": "Umbral pide a la app los shaders y TEMPS cada vez que arranca el juego.",
    "Unused Proton versions": "Versiones de Proton sin usar",
    "Use Gaming Deck's ReShade (no add-ons build) and IMPORT the preset; skip the DLL some presets ship.": "Usa el ReShade de Gaming Deck (la versión sin add-ons) e IMPORTA el preset; no hace falta la DLL que traen algunos presets.",
    "Use a Fandom wiki address, e.g. https://eldenring.fandom.com": "Usa una dirección de wiki de Fandom, p. ej. https://eldenring.fandom.com",
    "Uses the kernel's NTSYNC driver for Windows-style synchronisation: smoother frame times in some games. Needs a kernel with /dev/ntsync.": "Usa el driver NTSYNC del kernel para la sincronización estilo Windows: fotogramas más estables en algunos juegos. Necesita un kernel con /dev/ntsync.",
    "VAR=value VAR2=value (this game)": "VAR=valor VAR2=valor (este juego)",
    "VISUAL SHADERS": "SHADERS VISUALES",
    "Valve's compositor around the game: fixed resolution, upscaling, FPS limit or HDR; adds a little latency.": "El compositor de Valve alrededor del juego: resolución fija, escalado, límite de FPS o HDR; añade algo de latencia.",
    "Variable refresh rate (FreeSync / G-Sync) is on.": "La frecuencia de refresco variable (FreeSync / G-Sync) está activada.",
    "Variable refresh rate is off. In Hyprland, misc:vrr turns it on (2 = fullscreen apps only, good for games).": "La frecuencia de refresco variable está desactivada. En Hyprland, misc:vrr la activa (2 = solo apps a pantalla completa, bien para juegos).",
    "Visual shaders (ReShade / vkBasalt) for this game": "Shaders visuales (ReShade / vkBasalt) para este juego",
    "Visual shaders (vkBasalt): sharpening, anti-aliasing, ReShade presets": "Shaders visuales: nitidez, antialiasing y presets de ReShade",
    "Vulkan devices": "dispositivos Vulkan",
    "Vulkan loader": "cargador de Vulkan",
    "WHILE PLAYING": "MIENTRAS JUEGAS",
    "WRAPPING…": "ENVOLVIENDO…",
    "Web search for ReShade presets of this game on Nexus Mods": "Búsqueda web de presets de ReShade de este juego en Nexus Mods",
    "Web search for this game's ReShade presets on Nexus Mods": "Búsqueda web de presets de ReShade de este juego en Nexus Mods",
    "Which DirectX 12 feature level is reported to the game: for games that refuse to start without a newer one.": "Qué nivel de funciones de DirectX 12 se le dice al juego: para juegos que no arrancan sin uno más nuevo.",
    "Which DirectX 12 shader model is reported to the game: for games that check for a newer one.": "Qué shader model de DirectX 12 se le dice al juego: para juegos que comprueban uno más nuevo.",
    "Wine prefixes of uninstalled Steam games (each one is backed up first).": "Prefixes de Wine de juegos de Steam desinstalados (se hace copia de cada uno antes).",
    "Writes default_sched in /etc/scx_loader.toml (password): lavd Gaming from every boot": "Escribe default_sched en /etc/scx_loader.toml (contraseña): lavd Gaming desde cada arranque",
    "XeSS (newest)": "XeSS (más reciente)",
    "YOUR GAMES": "TUS JUEGOS",
    "Your saved preset: ": "Tu preset guardado: ",
    "achievements from Steam's own files · guides found for each game": "logros de los propios archivos de Steam · guías encontradas para cada juego",
    "after the game, e.g. -novid": "tras el juego, p. ej. -novid",
    "all good": "todo bien",
    "amdgpu kernel driver": "driver del kernel amdgpu",
    "args (replace the profile's)": "argumentos (sustituyen los del perfil)",
    "at boot: ": "al arrancar: ",
    "at its power limit: normal under load, odd at idle": "en su límite de consumo: normal con carga, raro en reposo",
    "autostart ": "autoarranque ",
    "available": "disponible",
    "before the game, e.g. gamescope -f --": "antes del juego, p. ej. gamescope -f --",
    "below 1048576: some games crash (see HEALTH)": "por debajo de 1048576: algunos juegos se cierran (mira SALUD)",
    "benchmark ": "prueba ",
    "changes to apply": "cambios por aplicar",
    "checking what it does…": "revisando qué hace…",
    "clean": "limpiar",
    "closed": "cerrado",
    "download it, then IMPORT": "descárgalo y pulsa IMPORTAR",
    "edit": "editar",
    "export": "exportar",
    "extra env: VAR=1 VAR2=x": "variables extra: VAR=1 VAR2=x",
    "fix": "arreglar",
    "from the first game that starts until the last one closes": "desde que empieza el primer juego hasta que se cierra el último",
    "from the start in games launched through the deck; in the others, once the panel has been opened": "desde el inicio en los juegos lanzados con el deck; en los demás, tras abrir el panel una vez",
    "game crashed": "juego cerrado con error",
    "game name on SweetFX Settings DB": "nombre del juego en SweetFX Settings DB",
    "game profile": "perfil de juego",
    "gamemode group": "grupo gamemode",
    "gaming import": "importar gaming",
    "group added: log out and back in": "grupo añadido: cierra sesión y vuelve a entrar",
    "imported file": "archivo importado",
    "in the gamemode group": "en el grupo gamemode",
    "in use": "en uso",
    "install": "instalar",
    "installed Steam games and Umbral games show up here": "aquí aparecen los juegos instalados de Steam y Umbral",
    "installed: ": "instalado: ",
    "kernel default (EEVDF)": "el del kernel (EEVDF)",
    "kernel sync for Wine/Proton": "sincronización del kernel para Wine/Proton",
    "last 5 minutes while STATUS is open": "últimos 5 minutos con ESTADO abierto",
    "launch": "lanzar",
    "lavd Gaming starts with each game and stops when it closes (only if no scheduler was running)": "lavd Gaming arranca con cada juego y se para al cerrarlo (solo si no había otro planificador)",
    "load ": "carga ",
    "missing loader: ": "falta el cargador: ",
    "multilib repository": "repositorio multilib",
    "name": "nombre",
    "never played": "sin jugar",
    "no achievements saved yet": "sin logros guardados aún",
    "no game  ·  Steam ": "ningún juego  ·  Steam ",
    "no key yet: pick one below": "sin tecla todavía: elige una abajo",
    "no lib32-pipewire / lib32-libpulse: 32-bit games have no sound": "sin lib32-pipewire / lib32-libpulse: los juegos de 32 bits no tienen sonido",
    "no orphans": "sin huérfanos",
    "no shaders possible": "sin shaders posibles",
    "no swappable upscaler DLL": "ninguna DLL de escalado sustituible",
    "no wiki found": "sin wiki encontrada",
    "none installed": "ninguno instalado",
    "not applied": "sin aplicar",
    "not available": "no disponible",
    "not in the gamemode group: it can't switch the governor": "no estás en el grupo gamemode: no puede cambiar el governor",
    "not in this kernel (needs 6.14 or newer); Proton falls back to esync/fsync": "no está en este kernel (necesita 6.14 o superior); Proton usa esync/fsync en su lugar",
    "not installed (optional)": "no instalado (opcional)",
    "not installed (optional: CPU governor and priorities while playing)": "no instalado (opcional: governor de la CPU y prioridades mientras juegas)",
    "not installed": "no instalado",
    "not installed: run install.sh": "no instalado: ejecuta install.sh",
    "nothing heavy to render right now": "ahora no tiene nada pesado que renderizar",
    "nothing to clean": "nada que limpiar",
    "off: Wayland sessions and gamescope need it; reboot after the fix": "desactivado: lo necesitan Wayland y gamescope; reinicia tras arreglarlo",
    "on (needed by Wayland and gamescope)": "activado (lo necesitan Wayland y gamescope)",
    "open": "abierto",
    "opens ReShade's menu in game": "abre el menú de ReShade en el juego",
    "other ": "otros ",
    "other: ALT + F1…": "otra: ALT + F1…",
    "p99 frame ms": "ms del fotograma p99",
    "paste a preset page (Nexus…) to keep it here": "pega una página de preset (Nexus…) para guardarla aquí",
    "permission ": "permiso ",
    "pipelines = Steam's Fossilize recordings (driver-independent, used to pre-compile) · driver = the GPU driver's compiled cache (NVIDIA nvidiav1 / Mesa for AMD-Intel), rebuilt after every driver update. DRIVER CACHE clears only that; ALL clears the game's whole folder. Either way the next launches stutter a little while caches rebuild.": "pipelines = grabaciones de Fossilize de Steam (independientes del driver, sirven para precompilar) · driver = la caché compilada del driver de la GPU (NVIDIA nvidiav1 / Mesa en AMD e Intel), que se rehace con cada actualización del driver. CACHÉ DEL DRIVER borra solo eso; TODO borra la carpeta entera del juego. En ambos casos los siguientes arranques darán algún tirón mientras se rehacen las cachés.",
    "play a game: a summary appears here when it closes": "juega a algo: al cerrarlo aparecerá aquí un resumen",
    "play": "jugar",
    "players with a GPU like yours": "jugadores con una GPU como la tuya",
    "players with your GPU vendor": "jugadores con tu marca de GPU",
    "prefix backup": "copia de prefix",
    "prefix clone": "clonar prefix",
    "prefix delete": "borrar prefix",
    "prefix restore": "restaurar prefix",
    "preset file: ": "archivo del preset: ",
    "preset pages you keep for this game (e.g. from Nexus)": "páginas de presets que guardas para este juego (p. ej. de Nexus)",
    "press ": "pulsa ",
    "proton install": "instalar proton",
    "protondb data": "datos de protondb",
    "reshade install": "instalar reshade",
    "reshade on": "reshade activado",
    "restore": "restaurar",
    "running": "en marcha",
    "save a preset page": "guarda una página de preset",
    "saves a screenshot with the effects to ": "guarda una captura con los efectos en ",
    "scx-tools not installed": "scx-tools no instalado",
    "scx_lavd in Gaming mode until you stop it or reboot (asks for your password)": "scx_lavd en modo Gaming hasta que lo pares o reinicies (pide tu contraseña)",
    "shader cache clean": "limpiar caché de shaders",
    "shader install": "instalar shaders",
    "shader not found in any known package": "shader no encontrado en ningún pack conocido",
    "shader packs: ": "packs de shaders: ",
    "snapshot": "snapshot",
    "state ": "estado ",
    "steam launch ": "lanzamiento steam ",
    "switches all effects on/off in game — compare, or drop them in heavy scenes": "activa o desactiva todos los efectos en el juego: para comparar o quitarlos en escenas pesadas",
    "the kernel has the module but it is not loaded": "el kernel trae el módulo pero no está cargado",
    "turns the effects on/off in game": "activa o desactiva los efectos en el juego",
    "uninstall": "desinstalar",
    "uninstalled app ": "app desinstalada ",
    "update": "actualizar",
    "updated ": "actualizado ",
    "visual shaders": "shaders visuales",
    "vkBasalt also works (via DXVK/VKD3D) if you prefer nothing in the game folder; presets get converted and lose depth effects.": "vkBasalt también funciona (vía DXVK/VKD3D) si prefieres no tocar la carpeta del juego; los presets se convierten y pierden los efectos de profundidad.",
    "vkBasalt comes from chaotic-aur, which isn't enabled here. Enable it (or build vkbasalt + lib32-vkbasalt from the AUR), then come back.": "vkBasalt viene de chaotic-aur, que no está activado aquí. Actívalo (o compila vkbasalt + lib32-vkbasalt desde AUR) y vuelve.",
    "vkBasalt is not recommended here: with converted presets this game can stay on a white screen.": "vkBasalt no se recomienda aquí: con presets convertidos este juego puede quedarse en pantalla blanca.",
    "vkBasalt isn't installed here → FX → INSTALL": "vkBasalt no está instalado aquí → FX → INSTALAR",
    "vkBasalt not installed": "vkBasalt no instalado",
    "while playing: ": "mientras juegas: ",
    "wiki: ": "wiki: ",
    "Δ B vs A": "Δ B frente a A",
    "≥ 1048576: enough for any game": "≥ 1048576: suficiente para cualquier juego",
    "■ STOP": "■ DETENER",
    "▶ PLAY": "▶ JUGAR",
    "◆ LAUNCHED THROUGH THE DECK": "◆ SE LANZA CON LA APP",
    "○ No shaders on this game": "○ Sin shaders en este juego",
    "○ Steam options: ": "○ Opciones de Steam: ",
    "● ACTIVE: ": "● ACTIVO: ",
    "● Launched through Gaming Deck": "● Se lanza a través de Gaming Deck",
    "● NEW VERSION": "● NUEVA VERSIÓN",
    "● READY": "● LISTO",
    "★ RECOMMENDED": "★ RECOMENDADO",
    "★ SUGGESTED FOR THIS PC": "★ SUGERIDO PARA ESTE PC",
    "⚠ Has online multiplayer/co-op: fine for single-player, check the game's rules online": "⚠ Tiene multijugador o cooperativo online: bien para un jugador, revisa las normas del juego online",
    "⚠ ONLINE GAME WITH ANTI-CHEAT (": "⚠ JUEGO ONLINE CON ANTI-CHEAT (",
    "⚠ Online multiplayer game: some online games forbid visual mods in their rules. Check before using shaders there.": "⚠ Juego multijugador online: algunos juegos online prohíben los mods visuales en sus normas. Compruébalo antes de usar shaders.",
    "⚠ This game doesn't launch through Gaming Deck yet, so the shaders won't load. ": "⚠ Este juego aún no se lanza a través de Gaming Deck, así que los shaders no se cargarán. ",
    "⚠ Umbral 0.10.0 or newer is needed: it asks the deck for shaders and TEMPS before starting the game. Update Umbral.": "⚠ Hace falta Umbral 0.10.0 o posterior: pide a la app los shaders y TEMPS antes de arrancar el juego. Actualiza Umbral.",
    "✓ Everything games need is in place (": "✓ Todo lo que necesitan los juegos está en orden (",
    "✓ SUMMARY": "✓ RESUMEN",
    "✔ Backup imported": "✔ Copia importada",
    "✔ Backup saved": "✔ Copia guardada",
    "✗ Anti-cheat (": "✗ Anti-cheat (",
    "✗ ReShade is banned or blocked in this game (PCGamingWiki): not touched": "✗ ReShade está vetado o bloqueado en este juego (PCGamingWiki): no se toca",
    "✘ It didn't work": "✘ No ha funcionado",
};
// sentences with values inside: [regex, replacement]
var PATTERNS = [
    [new RegExp("^(\\d+) SHARPENERS$"), "$1 ENFOQUES"],
    [new RegExp("^(\\d+) EFFECTS$"), "$1 EFECTOS"],
    [new RegExp("^(\\d+) sharpening effects stacked \\((.*)\\): halos and grain\\. One is enough\\.$"), "$1 efectos de nitidez a la vez ($2): halos y grano. Con uno basta."],
    [new RegExp("^(\\d+) sharpener\\(s\\) \\+ (\\d+) local-contrast effect\\(s\\) \\(Clarity…\\): too much detail enhancement, the image gets harsh\\.$"), "$1 de nitidez + $2 de contraste local (Clarity…): demasiado realce de detalle, la imagen queda dura."],
    [new RegExp("^Gamma / colour-space tools \\((.*)\\) are made for one monitor or HDR setup: on another they wash out or darken the picture\\.$"), "Herramientas de gamma / espacio de color ($1): están hechas para un monitor o un HDR concreto; en otro aclaran u oscurecen la imagen."],
    [new RegExp("^(\\d+) colour effects: a strong style of its own, not a fix — very different from the game's look\\.$"), "$1 efectos de color: un estilo fuerte, no una corrección; muy distinto del aspecto del juego."],
    [new RegExp("^Grain / chromatic aberration / vignette \\((.*)\\): a taste, many find them worse\\.$"), "Grano / aberración cromática / viñeta ($1): cuestión de gusto, a mucha gente le parecen peor."],
    [new RegExp("^(.*) read the depth buffer: if you see halos or shading on the UI, turn them off\\.$"), "$1 usan el búfer de profundidad: si ves halos o sombras sobre la interfaz, apágalos."],
    [new RegExp("^not installed: (\\d+) game profile\\(s\\) have GAMEMODE on and it does nothing$"), "no está instalado: $1 perfil(es) de juego tienen GAMEMODE activado y no hace nada"],
    [new RegExp("^Online game with anti-cheat \\((.*)\\): neither is safe there\\.$"), "Juego online con anti-cheat ($1): ninguno es seguro ahí."],
    [new RegExp("^Anti-cheat \\((.*)\\) that accepts plain ReShade: Elden Ring: popular ReShade presets \\(e\\.g\\. Nexus \"Unreal ReShade\"\\) are played online with Easy Anti-Cheat on\\.$"), "Anti-cheat ($1) que acepta ReShade normal: en Elden Ring los presets de ReShade más populares (p. ej. «Unreal ReShade» de Nexus) se juegan online con Easy Anti-Cheat activo."],
    [new RegExp("^(DirectX 10–12|DirectX 9|OpenGL|A Windows game) under Proton: ReShade itself runs presets exactly as made, depth effects included, with its in-game menu to tweak them\\.$"), "$1 con Proton: ReShade de verdad aplica los presets tal cual, con efectos de profundidad, y tiene su menú en el juego para ajustarlos."],
    [new RegExp("^Your current preset has (\\d+) depth effect\\(s\\) vkBasalt has to skip\\.$"), "Tu preset actual tiene $1 efecto(s) de profundidad que vkBasalt tendría que omitir."],
    [new RegExp("^missing: (.*)$"), "falta: $1"],
    [new RegExp("^loaded(.*)$"), "cargado$1"],
    [new RegExp("^enabled in (.*) \\(32-bit libraries for Steam and Wine\\)$"), "activado en $1 (librerías de 32 bits para Steam y Wine)"],
    [new RegExp("^(.*) present: Proton/Wine can use kernel sync$"), "$1 presente: Proton/Wine pueden usar la sincronización del kernel"],
    [new RegExp("^no NVIDIA, AMD or Intel GPU found in (.*)$"), "no se encontró ninguna GPU NVIDIA, AMD ni Intel en $1"],
    [new RegExp("^install vulkan-tools to check which GPUs Vulkan sees \\(drivers: (.*)\\)$"), "instala vulkan-tools para ver qué GPUs ve Vulkan (drivers: $1)"],
];
